package visual;

/**
 *
 * @author Cloud
 */
public class Administracao extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Administracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEscolha = new javax.swing.ButtonGroup();
        scrollUltReservas = new javax.swing.JScrollPane();
        tableUsuario = new javax.swing.JTable();
        scrollDisponiveis = new javax.swing.JScrollPane();
        tableLaboratorios = new javax.swing.JTable();
        painelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        painelRodape = new javax.swing.JPanel();
        botaoAlterar = new javax.swing.JButton();
        labelPessoasCadastrdas = new javax.swing.JLabel();
        labelPessoasCadastrdas1 = new javax.swing.JLabel();
        botaoAlterar1 = new javax.swing.JButton();

        tableUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome:", "CPF:", "Senha:", "Ocupação:", "Curso / Função:"
            }
        ));
        scrollUltReservas.setViewportView(tableUsuario);

        tableLaboratorios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Laboratório", "Hora Inicial", "Hora Final", "Title 4"
            }
        ));
        scrollDisponiveis.setViewportView(tableLaboratorios);

        painelTitulo.setPreferredSize(new java.awt.Dimension(571, 90));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Administração");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(labelTitulo))
        );

        painelRodape.setPreferredSize(new java.awt.Dimension(0, 90));

        javax.swing.GroupLayout painelRodapeLayout = new javax.swing.GroupLayout(painelRodape);
        painelRodape.setLayout(painelRodapeLayout);
        painelRodapeLayout.setHorizontalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        painelRodapeLayout.setVerticalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        botaoAlterar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoAlterar.setText("Alterar");

        labelPessoasCadastrdas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPessoasCadastrdas.setText("Pessoas cadastradas:");

        labelPessoasCadastrdas1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPessoasCadastrdas1.setText("Laboratórios cadastrados:");

        botaoAlterar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoAlterar1.setText("Alterar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addComponent(painelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPessoasCadastrdas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoAlterar1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPessoasCadastrdas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoAlterar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrollUltReservas)
                        .addComponent(scrollDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterar)
                    .addComponent(labelPessoasCadastrdas))
                .addGap(18, 18, 18)
                .addComponent(scrollUltReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterar1)
                    .addComponent(labelPessoasCadastrdas1))
                .addGap(18, 18, 18)
                .addComponent(scrollDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoAlterar1;
    private javax.swing.ButtonGroup buttonEscolha;
    private javax.swing.JLabel labelPessoasCadastrdas;
    private javax.swing.JLabel labelPessoasCadastrdas1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelRodape;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JScrollPane scrollDisponiveis;
    private javax.swing.JScrollPane scrollUltReservas;
    private javax.swing.JTable tableLaboratorios;
    private javax.swing.JTable tableUsuario;
    // End of variables declaration//GEN-END:variables
}
