package visual;

import conexao.Conexao;
import conexao.Teste;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Alucarde
 */
public class TelaLogin extends javax.swing.JPanel {
    /**
     * Creates new form TelaLogin
     */
    private static String usuario;
    private static String cpf;
    
    public TelaLogin() {
        initComponents();
        
    }
    
    // geter das variaveis
    public static String getUsuario(){
        return usuario;
    }
    public static String getCpf(){
        return cpf;
    }
    // seter da variavel
    public void setUsuario(String usuario){
        this.usuario = usuario;
    }
    public void setCpf(String cpf){
        this.cpf = cpf;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAcessar = new javax.swing.JButton();
        fieldCpf = new javax.swing.JTextField();
        fieldSenha = new javax.swing.JPasswordField();
        labelCpf = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelTitilo = new javax.swing.JLabel();
        labelLogar = new javax.swing.JLabel();
        painelRodape = new javax.swing.JPanel();
        labelCadastrar = new javax.swing.JLabel();

        buttonAcessar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAcessar.setText("Acessar");
        buttonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcessarActionPerformed(evt);
            }
        });

        fieldCpf.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        fieldSenha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        fieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSenhaActionPerformed(evt);
            }
        });

        labelCpf.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelCpf.setText("CPF:");

        labelSenha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelSenha.setText("Senha:");

        labelTitilo.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        labelTitilo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitilo.setText("LabControl");
        labelTitilo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelLogar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelLogar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogar.setText("Logar:");
        labelLogar.setToolTipText("");

        painelRodape.setPreferredSize(new java.awt.Dimension(0, 90));

        labelCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCadastrar.setText("Se não possuir cadastro aperte o botão \"Cadastrar\" na barra do lado esquerdo");

        javax.swing.GroupLayout painelRodapeLayout = new javax.swing.GroupLayout(painelRodape);
        painelRodape.setLayout(painelRodapeLayout);
        painelRodapeLayout.setHorizontalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRodapeLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(labelCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRodapeLayout.setVerticalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRodapeLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(labelCadastrar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(labelLogar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(buttonAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(239, 239, 239))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldCpf)
                                .addComponent(fieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                                .addComponent(labelSenha)))))
                .addContainerGap(181, Short.MAX_VALUE))
            .addComponent(painelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
            .addComponent(labelTitilo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labelTitilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(labelLogar)
                .addGap(35, 35, 35)
                .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldSenha)
                .addGap(65, 65, 65)
                .addComponent(buttonAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(painelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcessarActionPerformed
        String senha = new String(this.getFieldSenha().getPassword());
        
        Teste t = new Teste();
            
            t.setConexao(new Conexao());
        try {
            t.getConexao().conectar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try { // pesquisar reservas no banco
            t.getConexao().logar(this.getFieldCpf().getText(), senha);
            String nome = t.getConexao().logar(this.getFieldCpf().getText(), senha);

            if(nome != null){
                this.setUsuario(nome);//setUsuario();
                this.setCpf(this.getFieldCpf().getText());
                JOptionPane.showMessageDialog(null, "Bem vindo(a) " + nome + "!");
            }
            else{
                JOptionPane.showMessageDialog(null, "CPF e/ou Senha não cadastrado!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } // fim da pesquisa de reservas

    }//GEN-LAST:event_buttonAcessarActionPerformed

    private void fieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcessar;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JLabel labelCadastrar;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelLogar;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTitilo;
    private javax.swing.JPanel painelRodape;
    // End of variables declaration//GEN-END:variables

    // geters dos componentes
    public JTextField getFieldCpf(){
        return fieldCpf;
    }
    public JPasswordField getFieldSenha(){
        return fieldSenha;
    }    
}
