package visual;

/**
 * Classe para criação da tela empresa
 * @author Jailson Joé dos Santos Silva
 * @version 1.0
 * @since  realese 01 da aplicação
 */
public class TelaEmpresa extends javax.swing.JPanel {

    /**
     * Construtor da classe Empresa
     */
    public TelaEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInformativo = new javax.swing.JPanel();
        labelCep = new javax.swing.JLabel();
        labelContatos = new javax.swing.JLabel();
        labelTelUm = new javax.swing.JLabel();
        labelTelDois = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelEmpresa = new javax.swing.JLabel();
        labelInstituicao = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        labelRua = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        separadorInferior = new javax.swing.JSeparator();
        separadorSuperior = new javax.swing.JSeparator();

        painelInformativo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));

        labelCep.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCep.setText("CEP: 55.292-270");

        labelContatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelContatos.setText("Contatos:");

        labelTelUm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTelUm.setText("(87) 3764-5505");

        labelTelDois.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTelDois.setText("(87) 3764-5551");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Empresa");

        labelEmpresa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelEmpresa.setText("Universidade Federal Rural de Pernambuco");

        labelInstituicao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelInstituicao.setText("UAG - Unidade Acadêmica de Garanhuns");

        labelEndereco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelEndereco.setText("Endereço:");

        labelRua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelRua.setText("Av. Bom Pastor,  s/n");

        labelBairro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelBairro.setText("Boa Vista Garanhuns/PE");

        javax.swing.GroupLayout painelInformativoLayout = new javax.swing.GroupLayout(painelInformativo);
        painelInformativo.setLayout(painelInformativoLayout);
        painelInformativoLayout.setHorizontalGroup(
            painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorSuperior, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(painelInformativoLayout.createSequentialGroup()
                .addGroup(painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInformativoLayout.createSequentialGroup()
                        .addGroup(painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelInformativoLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTitulo)
                                    .addComponent(labelTelDois)
                                    .addComponent(labelTelUm)
                                    .addComponent(labelContatos)
                                    .addComponent(labelInstituicao)
                                    .addComponent(labelEmpresa)))
                            .addGroup(painelInformativoLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCep)
                                    .addComponent(labelBairro)
                                    .addComponent(labelRua)
                                    .addComponent(labelEndereco))))
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addComponent(separadorInferior, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        painelInformativoLayout.setVerticalGroup(
            painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformativoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelTitulo)
                .addGap(35, 35, 35)
                .addComponent(labelEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInstituicao)
                .addGap(31, 31, 31)
                .addComponent(separadorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelEndereco)
                .addGap(18, 18, 18)
                .addComponent(labelRua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCep)
                .addGap(33, 33, 33)
                .addComponent(separadorInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelContatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTelUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTelDois)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(painelInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(painelInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelContatos;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelInstituicao;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelTelDois;
    private javax.swing.JLabel labelTelUm;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelInformativo;
    private javax.swing.JSeparator separadorInferior;
    private javax.swing.JSeparator separadorSuperior;
    // End of variables declaration//GEN-END:variables
}
