package visual;

import conexao.Conexao;
import conexao.Teste;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import modelo.ModeloTabela;

/**
 *
 * @author Cloud
 */
public class TelaPesquisa extends javax.swing.JPanel implements interfaces.IManipulacaoVisual{

    /**
     * Creates new form TelaPesquisa
     */
    TelaPrincipal tela;
    JPanel novoPainel;
    public TelaPesquisa() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLaboratorio = new javax.swing.JLabel();
        comboBoxLaboratorio = new javax.swing.JComboBox();
        painelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        painelRodape1 = new javax.swing.JPanel();
        botaoPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReserva = new javax.swing.JTextArea();

        labelLaboratorio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelLaboratorio.setText("Escolha o laboratório:");

        comboBoxLaboratorio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboBoxLaboratorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11", "12", "13", "14", "21", "22", "23", "24" }));

        painelTitulo.setPreferredSize(new java.awt.Dimension(571, 90));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Pesquisa");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(labelTitulo)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(labelTitulo))
        );

        painelRodape1.setPreferredSize(new java.awt.Dimension(0, 90));

        botaoPesquisar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRodape1Layout = new javax.swing.GroupLayout(painelRodape1);
        painelRodape1.setLayout(painelRodape1Layout);
        painelRodape1Layout.setHorizontalGroup(
            painelRodape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRodape1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoPesquisar)
                .addGap(388, 388, 388))
        );
        painelRodape1Layout.setVerticalGroup(
            painelRodape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRodape1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(botaoPesquisar)
                .addGap(26, 26, 26))
        );

        tabelaReserva.setColumns(20);
        tabelaReserva.setRows(5);
        jScrollPane1.setViewportView(tabelaReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addComponent(painelRodape1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLaboratorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLaboratorio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBoxLaboratorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(painelRodape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        Teste t = new Teste();

		t.setConexao(new Conexao());
        try {
            t.getConexao().conectar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try { // pesquisar reservas no banco
            t.getConexao().retornarReservaLab(this.getBoxLaboratorio().getSelectedItem().toString());
            ArrayList<modelo.Reserva> dados = t.getConexao().retornarReservaLab(this.getBoxLaboratorio().getSelectedItem().toString());
            ModeloTabela modelo = new ModeloTabela(dados);
            
            int i = 0;
            ArrayList<String> dadosReserva = new ArrayList();
            
            while(i < dados.size()){
                
                dadosReserva.add("    " + dados.get(i).getLaboratorio() + "    ");
                dadosReserva.add(dados.get(i).getIdPessoa());
                dadosReserva.add(dados.get(i).getHoraInicial());
                dadosReserva.add(dados.get(i).getHoraFinal());
                dadosReserva.add(dados.get(i).getData() + "\n");
                
                i++;
            }
            this.tabelaReserva.setText("Laboratório: Nome: Hora Inicial:  Hora Final:  Data:  \n\n" + dadosReserva);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } // fim da pesquisa de reservas
    }//GEN-LAST:event_botaoPesquisarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JComboBox comboBoxLaboratorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelLaboratorio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelRodape1;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JTextArea tabelaReserva;
    // End of variables declaration//GEN-END:variables
    
    public JComboBox getBoxLaboratorio(){
        return comboBoxLaboratorio;
    }
}
