package visual;

import conexao.Conexao;
import conexao.Teste;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 * Classe para criação da tela administração
 * @author Jailson José dos Santos Silva
 */
public class TelaAdministracao extends javax.swing.JPanel {

    /**
     * Contrutor da lasse Administracao
     */
    public TelaAdministracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEscolha = new javax.swing.ButtonGroup();
        painelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        botaoPesquisarPessoa = new javax.swing.JButton();
        labelPessoasCadastrdas = new javax.swing.JLabel();
        labelPessoasCadastrdas1 = new javax.swing.JLabel();
        botaoPesquisarLab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldPessoa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldLaboratorio = new javax.swing.JTextArea();
        labelCadastros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        botaoPesquisarLabMaisUsados = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldLabMaisUsados = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        labelInformacao = new javax.swing.JLabel();
        botaoAlterarPessoa = new javax.swing.JButton();
        labelCpf = new javax.swing.JLabel();
        fieldCpf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelNome = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        labelDadosAlterados = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelDicaAlteracao = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();

        painelTitulo.setPreferredSize(new java.awt.Dimension(571, 90));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Administração");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(labelTitulo)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(labelTitulo))
        );

        botaoPesquisarPessoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoPesquisarPessoa.setText("Pesquisar");
        botaoPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarPessoaActionPerformed(evt);
            }
        });

        labelPessoasCadastrdas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPessoasCadastrdas.setText("Pessoas:");

        labelPessoasCadastrdas1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPessoasCadastrdas1.setText("Laboratórios:");

        botaoPesquisarLab.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoPesquisarLab.setText("Pesquisar");
        botaoPesquisarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarLabActionPerformed(evt);
            }
        });

        fieldPessoa.setColumns(20);
        fieldPessoa.setRows(5);
        jScrollPane1.setViewportView(fieldPessoa);

        fieldLaboratorio.setColumns(20);
        fieldLaboratorio.setRows(5);
        jScrollPane2.setViewportView(fieldLaboratorio);

        labelCadastros.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCadastros.setText("Cadastros:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Uso dos laboratórios:");

        botaoPesquisarLabMaisUsados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoPesquisarLabMaisUsados.setText("Pesquisar");
        botaoPesquisarLabMaisUsados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarLabMaisUsadosActionPerformed(evt);
            }
        });

        fieldLabMaisUsados.setColumns(20);
        fieldLabMaisUsados.setRows(5);
        jScrollPane3.setViewportView(fieldLabMaisUsados);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Alterar Informações:");

        labelInformacao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelInformacao.setText("Informações:");

        botaoAlterarPessoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoAlterarPessoa.setText("Alterar");
        botaoAlterarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarPessoaActionPerformed(evt);
            }
        });

        labelCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCpf.setText("CPF:");

        fieldCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNome.setText("Nome:");

        fieldNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSenha.setText("Senha:");

        labelDadosAlterados.setText("Dados que para serem alterados;");

        jLabel6.setText("jLabel6");

        labelDicaAlteracao.setText("CPF da pessoa que tera os dados alterados;");

        fieldSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCadastros)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPessoasCadastrdas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoPesquisarLab))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPessoasCadastrdas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoPesquisarPessoa))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fieldNome))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addComponent(botaoAlterarPessoa))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6))
                        .addComponent(labelInformacao)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelCpf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldCpf))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoPesquisarLabMaisUsados))
                        .addComponent(jSeparator3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelSenha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fieldSenha)))
                    .addComponent(labelDadosAlterados)
                    .addComponent(labelDicaAlteracao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInformacao)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoPesquisarLabMaisUsados)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDicaAlteracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCpf))
                                .addGap(4, 4, 4)
                                .addComponent(labelDadosAlterados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNome)
                                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSenha)
                                    .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoAlterarPessoa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCadastros)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoPesquisarPessoa)
                            .addComponent(labelPessoasCadastrdas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoPesquisarLab)
                            .addComponent(labelPessoasCadastrdas1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addGap(0, 103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarPessoaActionPerformed
        Teste t = new Teste(); // instancia Teste paara fazer a conexao

		t.setConexao(new Conexao()); // seta os valores para conexão
        try {
            t.getConexao().conectar(); // conecta ao banco
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try { // pesquisar pessoas no banco
            t.getConexao().retornarDadosPessoa(); // captura os dados de retorno se ouver
            ArrayList<String> dados = t.getConexao().retornarDadosPessoa(); // cria um ArrayList com os dados
            
            this.fieldPessoa.setText("Nome: CPF:        \n\n" + dados); // inseri uma String na area de exto
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } // fim da pesquisa de pessoas cadastradas
    }//GEN-LAST:event_botaoPesquisarPessoaActionPerformed

    private void botaoPesquisarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarLabActionPerformed
        Teste t = new Teste(); // instancia Teste paara fazer a conexao

		t.setConexao(new Conexao()); // seta os valores para conexão
        try {
            t.getConexao().conectar(); // conecta ao banco
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try { // pesquisar laboratorios disponiveis no banco
                        
            t.getConexao().retornarLabDisponivel(); // captura os dados de retorno se ouver
            ArrayList<String> dadosLab = t.getConexao().retornarLabDisponivel(); // cria um ArrayList com os dados
            
            this.fieldLaboratorio.setText("Laboratorio:\n\n" + dadosLab);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar a pesquisa!");
        } // fim da pesquisa de laboratorios disponiveis no banco
    }//GEN-LAST:event_botaoPesquisarLabActionPerformed

    private void botaoPesquisarLabMaisUsadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarLabMaisUsadosActionPerformed
        Teste t = new Teste(); // instancia Teste paara fazer a conexao

		t.setConexao(new Conexao()); // seta os valores para conexão
        try {
            t.getConexao().conectar(); // conecta ao banco
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try { // pesquisar laboratorios mais reservados
                        
            t.getConexao().labsMaisUsados(); // captura os dados de retorno se ouver
            ArrayList<String> dadosLab = t.getConexao().labsMaisUsados(); // cria um ArrayList com os dados
            
            this.fieldLabMaisUsados.setText("Laboratorio: Nº de reservas\n\n" + dadosLab);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar a pesquisa!");
        } // fim da pesquisa de laboratorios mais reservados
    }//GEN-LAST:event_botaoPesquisarLabMaisUsadosActionPerformed

    private void botaoAlterarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarPessoaActionPerformed
        Teste t = new Teste(); // instancia Teste paara fazer a conexao

		t.setConexao(new Conexao()); // seta os valores para conexão
        try {
            t.getConexao().conectar(); // conecta ao banco
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try { // altera os dados de uma pessoa 
            
            String senha = new String(this.getFieldSenha().getPassword()); // cria uma string com a senha
            
            if(this.fieldCpf.getText() == null || "".equals(this.fieldCpf.getText())){ // checa se o usuario informou o cpf
                JOptionPane.showMessageDialog(null, "Por favor digite o cpf da pessoa!"); // se não informou mostra essa mensagem
            }else{ // se informou executa essa ação
                
                
                t.getConexao().alterarPessoa(this.fieldCpf.getText(), this.fieldNome.getText(), senha); // altera os dados informados
                JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
            }            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar a alteração!");
        } // fim da alteração de dados de uma pessoa
    }//GEN-LAST:event_botaoAlterarPessoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarPessoa;
    private javax.swing.JButton botaoPesquisarLab;
    private javax.swing.JButton botaoPesquisarLabMaisUsados;
    private javax.swing.JButton botaoPesquisarPessoa;
    private javax.swing.ButtonGroup buttonEscolha;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JTextArea fieldLabMaisUsados;
    private javax.swing.JTextArea fieldLaboratorio;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextArea fieldPessoa;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelCadastros;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDadosAlterados;
    private javax.swing.JLabel labelDicaAlteracao;
    private javax.swing.JLabel labelInformacao;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPessoasCadastrdas;
    private javax.swing.JLabel labelPessoasCadastrdas1;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelTitulo;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Método paara captura do componente fieldCpf
     * @author Jailson José dos Santos Silva
     * @return JTextField - retorna o componente fieldCpf
     */
    public JTextField getFieldCpf(){
        return fieldCpf;
    }
    
    /**
     * Método paara captura do componente fieldNome
     * @author Jailson José dos Santos Silva
     * @return JTextField - retorna o componente fieldNome
     */
    public JTextField getFieldNome(){
        return fieldNome;
    }
    
    /**
     * Método paara captura do componente fieldSenha
     * @author Jailson José dos Santos Silva
     * @return JTextField - retorna o componente fieldSenha
     */
    public JPasswordField getFieldSenha(){
        return fieldSenha;
    }
}
