package visual;

import conexao.Conexao;
import conexao.Teste;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Alucarde
 */
public class TelaReserva extends javax.swing.JPanel {

    /**
     * Creates new form Pesquisar
     */
    
    MaskFormatter formHora;
    MaskFormatter formData;
    public TelaReserva() throws ParseException {
        initComponents();
        this.formHora = new MaskFormatter("##/##");
        this.formData = new MaskFormatter("##/##/####");
    }
    private MaskFormatter setMascara(String mascara){  
    MaskFormatter mask = null;  
    try{  
        mask = new MaskFormatter(mascara);                        
        }catch(java.text.ParseException ex){}  
    return mask;  
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxLaboratorio = new javax.swing.JComboBox();
        labelLaboratorio = new javax.swing.JLabel();
        labelHoraInicial = new javax.swing.JLabel();
        labelHoraFinal = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        fieldHoraFinal = new javax.swing.JFormattedTextField(setMascara("##:##"));
        fieldData = new javax.swing.JFormattedTextField(setMascara("####/##/##"));
        fieldHoraInicial = new javax.swing.JFormattedTextField(setMascara("##:##"));
        painelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        painelRodape = new javax.swing.JPanel();
        botaoConfirmar = new javax.swing.JButton();
        labelReserva = new javax.swing.JLabel();

        comboBoxLaboratorio.setEditable(true);
        comboBoxLaboratorio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboBoxLaboratorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11", "12", "13", "14", "21", "22", "23", "24" }));
        comboBoxLaboratorio.setToolTipText("");
        comboBoxLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLaboratorioActionPerformed(evt);
            }
        });

        labelLaboratorio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelLaboratorio.setText("Escolha o laboratório:");

        labelHoraInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelHoraInicial.setText("Horário inicial:");

        labelHoraFinal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelHoraFinal.setText("Horário final:");

        labelData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelData.setText("Informe a data:");

        fieldHoraFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldHoraFinal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        fieldData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        fieldHoraInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldHoraInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        painelTitulo.setPreferredSize(new java.awt.Dimension(571, 90));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Reserva");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(labelTitulo))
        );

        painelRodape.setPreferredSize(new java.awt.Dimension(0, 90));

        botaoConfirmar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        labelReserva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelReserva.setText("Confirmar reserva:");

        javax.swing.GroupLayout painelRodapeLayout = new javax.swing.GroupLayout(painelRodape);
        painelRodape.setLayout(painelRodapeLayout);
        painelRodapeLayout.setHorizontalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRodapeLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(labelReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoConfirmar)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        painelRodapeLayout.setVerticalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRodapeLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmar)
                    .addComponent(labelReserva))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addComponent(painelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLaboratorio)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelData)
                        .addGap(18, 18, 18)
                        .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHoraInicial)
                            .addComponent(fieldHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHoraFinal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLaboratorio)
                    .addComponent(comboBoxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoraInicial)
                    .addComponent(labelHoraFinal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(painelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLaboratorioActionPerformed
        this.comboBoxLaboratorio.revalidate();
    }//GEN-LAST:event_comboBoxLaboratorioActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        Teste t = new Teste();
		
	System.out.println(getFieldHoraInicial().getText());
        System.out.println(this.getComboBoxLaboratorio().getToolTipText());
        
	t.setConexao(new Conexao());
        try {
            
            t.getConexao().conectar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try { // Reservar horario do laboratorio
            
            t.getConexao().reservarHorario(this.getComboBoxLaboratorio().getSelectedItem().toString(), TelaLogin.getCpf(),getFieldData().getText(), this.getFieldHoraInicial().getText(), this.getFieldHoraFinal().getText());
            
            } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } // fim de inserir pessoa
    }//GEN-LAST:event_botaoConfirmarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JComboBox comboBoxLaboratorio;
    private javax.swing.JFormattedTextField fieldData;
    private javax.swing.JFormattedTextField fieldHoraFinal;
    private javax.swing.JFormattedTextField fieldHoraInicial;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelHoraFinal;
    private javax.swing.JLabel labelHoraInicial;
    private javax.swing.JLabel labelLaboratorio;
    private javax.swing.JLabel labelReserva;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelRodape;
    private javax.swing.JPanel painelTitulo;
    // End of variables declaration//GEN-END:variables
    
    // geters dos componentes
    public JComboBox getComboBoxLaboratorio(){
        return comboBoxLaboratorio;
    }
    public JFormattedTextField getFieldData(){
        return fieldData;
    }
    public JFormattedTextField getFieldHoraInicial(){
        return fieldHoraInicial;
    }
    public JFormattedTextField getFieldHoraFinal(){
        return fieldHoraFinal;
    }
}
